version: '3'
services:
  doc_container_2:
    build: './consumers/web'
    # Host port proxy to 80
    ports:
      - "3000:3000"
    volumes:
      - ./consumers/web:/consumers/web
    environment:
      # If a production enviroment is desired, set the APP_ENV variable to production
      # APP_ENV: 'production'
      APP_ENV: 'development'
    links:
      - doc_container_1

  doc_container_1:
    build: './api'
    restart: always
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:
      - "./api:/api"
